# Generated by Django 3.2.8 on 2022-01-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
