# Generated by Django 3.1.5 on 2021-04-01 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Youtube', 'Youtube')], max_length=200, null=True)),
                ('category_2', models.CharField(choices=[('Like', 'Like'), ('Share', 'Share'), ('Comment', 'Comment'), ('Mention', 'Mention'), ('Follow', 'Follow'), ('Repost', 'Repost'), ('Hastag', 'Hashtag'), ('Watch', 'Watch'), ('Re-tweet', 'Re-tweet'), ('Suscribe', 'Suscribe'), ('Like and Comment', 'Like and Comment'), ('Like, Comment and Share', 'Like, Comment and Share')], max_length=200, null=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('link', models.URLField(max_length=500, null=True)),
                ('task_expiry_date', models.DateField(max_length=200, null=True)),
                ('task_expiry_time', models.TimeField(null=True)),
                ('general', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('message', models.TextField(max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name', max_length=100, null=True)),
                ('email', models.EmailField(help_text='Email', max_length=100, null=True)),
                ('twitter_id', models.CharField(help_text='Twitter ID', max_length=100, null=True)),
                ('instagram_id', models.CharField(help_text='Instagram ID', max_length=100, null=True)),
                ('youtube_id', models.CharField(help_text='Youtube ID', max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, default='pro.png', null=True, upload_to='avatars')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=200, null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.admintask')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.worker')),
            ],
        ),
        migrations.CreateModel(
            name='PaidTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('payment_complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.worker')),
            ],
        ),
        migrations.AddField(
            model_name='admintask',
            name='worker',
            field=models.ManyToManyField(to='task.Worker'),
        ),
    ]
