# Generated by Django 3.2.8 on 2022-01-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_worker_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='code',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
