# Generated by Django 3.1.5 on 2021-04-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210401_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='Full name', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_id',
            field=models.CharField(help_text='Instagram ID', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(help_text='Twitter ID', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube_id',
            field=models.CharField(help_text='Youtube ID', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(help_text='Email', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='full_name',
            field=models.CharField(help_text='Full name', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='instagram_id',
            field=models.CharField(help_text='Instagram ID', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='twitter_id',
            field=models.CharField(help_text='Twitter ID', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='youtube_id',
            field=models.CharField(help_text='Youtube ID', max_length=25, null=True),
        ),
    ]
