# Generated by Django 3.2.8 on 2022-01-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220107_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_expiry_time',
            field=models.TimeField(default='03-21-28', null=True),
        ),
        migrations.RemoveField(
            model_name='task',
            name='worker',
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.worker'),
        ),
    ]
