# Generated by Django 3.1.5 on 2021-04-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210403_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintask',
            name='general',
            field=models.BooleanField(default=True),
        ),
    ]
