# Generated by Django 3.1.5 on 2021-04-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210403_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(help_text='Email', max_length=25, null=True, unique=True),
        ),
    ]
