# Generated by Django 3.2.8 on 2022-01-11 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20220111_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 11, 19, 36, 34, 555432, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 11, 19, 36, 34, 555432, tzinfo=utc), null=True),
        ),
    ]
