# Generated by Django 3.1.5 on 2021-04-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20210407_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(help_text='Email', max_length=25, null=True),
        ),
    ]
