# Generated by Django 3.2.8 on 2022-01-12 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20220111_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 18, 43, 2, 984798, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 12, 18, 43, 2, 984798, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_earnings', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('verified_earnings', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('disapproved_earnings', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='task.worker')),
            ],
        ),
    ]
