# Generated by Django 3.1.5 on 2021-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20210408_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube_id',
            field=models.CharField(help_text='Youtube ID', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(help_text='Email', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='youtube_id',
            field=models.CharField(help_text='Youtube ID', max_length=40, null=True),
        ),
    ]
