# Generated by Django 3.1.5 on 2021-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20210409_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram_id',
            field=models.CharField(help_text='Instagram ID', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(help_text='Twitter ID', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='instagram_id',
            field=models.CharField(help_text='Instagram ID', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='twitter_id',
            field=models.CharField(help_text='Twitter ID', max_length=30, null=True),
        ),
    ]
