# Generated by Django 3.2.8 on 2022-01-12 19:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20220112_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisapprovedEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disapproved_earnings', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disapproved_earnings', to='task.worker')),
            ],
        ),
        migrations.CreateModel(
            name='PendingEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_earnings', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_earnings', to='task.worker')),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_earnings', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_earnings', to='task.worker')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawnEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disapproved_earnings', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawn_earnings', to='task.worker')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 19, 0, 6, 910108, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 12, 19, 0, 6, 910108, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='Earnings',
        ),
    ]
