# Generated by Django 3.1.5 on 2021-04-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20210409_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admintask',
            name='general',
        ),
    ]
