# Generated by Django 3.2.8 on 2022-01-12 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20220112_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawnearnings',
            old_name='disapproved_earnings',
            new_name='withdrawn_earnings',
        ),
        migrations.AddField(
            model_name='pendingearnings',
            name='disapproved_earnings',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='pendingearnings',
            name='verified_earnings',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='pendingearnings',
            name='withdrawn_earnings',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='pendingearnings',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='task.worker'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 19, 7, 40, 363905, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 12, 19, 7, 40, 363905, tzinfo=utc), null=True),
        ),
    ]
