# Generated by Django 3.1.5 on 2021-04-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_remove_admintask_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintask',
            name='general',
            field=models.BooleanField(default=True),
        ),
    ]
