# Generated by Django 3.1.5 on 2021-04-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_admintask_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admintask',
            name='general',
        ),
    ]
