# Generated by Django 3.2.8 on 2022-01-12 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20220112_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingEarnings',
            new_name='Earnings',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 19, 24, 19, 202491, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 12, 19, 24, 19, 202491, tzinfo=utc), null=True),
        ),
    ]
