# Generated by Django 3.2.8 on 2022-01-13 02:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20220112_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_address', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='verifiedearnings',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='withdrawnearnings',
            name='worker',
        ),
        migrations.AddField(
            model_name='worker',
            name='paypal_address',
            field=models.EmailField(help_text='Paypal Address', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='disapproved_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='pending_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='verified_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='withdrawn_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 13, 2, 22, 38, 222026, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 13, 2, 22, 38, 222026, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='DisapprovedEarnings',
        ),
        migrations.DeleteModel(
            name='VerifiedEarnings',
        ),
        migrations.DeleteModel(
            name='WithdrawnEarnings',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to='task.worker'),
        ),
    ]
