# Generated by Django 3.2.8 on 2022-01-13 21:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20220113_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='complaints',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 21, 53, 47, 212022, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='earnings',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 21, 53, 47, 212022, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='suscribers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 21, 53, 47, 212022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 21, 53, 47, 212022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 13, 21, 53, 47, 212022, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 13, 21, 53, 47, 212022, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 21, 53, 47, 212022, tzinfo=utc)),
        ),
    ]
