# Generated by Django 3.2.8 on 2022-01-14 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_auto_20220113_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField(blank=True, max_length=8000, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, max_length=700, null=True)),
                ('twitter', models.URLField(blank=True, max_length=700, null=True)),
                ('instagram', models.URLField(blank=True, max_length=700, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='complaints',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 12, 36, 52, 13, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 12, 36, 51, 976014, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 12, 36, 52, 13, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suscribers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 12, 36, 51, 976014, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 12, 36, 51, 992013, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_expiry_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 14, 12, 36, 51, 992013, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 12, 36, 52, 13, tzinfo=utc)),
        ),
    ]
