# Generated by Django 3.2.8 on 2022-01-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_auto_20220114_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
