# Generated by Django 3.2.8 on 2022-01-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_about_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='facebook',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='instagram',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='linkedin',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='twitter',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
