# Generated by Django 3.2.8 on 2022-01-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_auto_20220114_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category_2',
            field=models.CharField(choices=[('Like', 'Like'), ('Share', 'Share'), ('Comment', 'Comment'), ('Mention', 'Mention'), ('Follow', 'Follow'), ('Repost', 'Repost'), ('Hastag', 'Hashtag'), ('Watch', 'Watch'), ('Re-tweet', 'Re-tweet'), ('Suscribe', 'Suscribe'), ('Like & Comment', 'Like & Comment')], max_length=200, null=True),
        ),
    ]
