# Generated by Django 3.2.8 on 2022-01-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_auto_20220117_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='paid_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, null=True),
        ),
    ]
