# Generated by Django 3.2.8 on 2022-01-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='who_updated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
