# Generated by Django 3.2.8 on 2022-01-19 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_task_who_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_to2', to='task.worker'),
        ),
    ]
