# Generated by Django 3.2.8 on 2022-01-19 22:35

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_notification_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_expiry_date',
            field=models.DateField(default=task.models.f, null=True),
        ),
    ]
