# Generated by Django 3.2.8 on 2022-01-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0029_alter_task_task_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube_id',
        ),
    ]
