# Generated by Django 3.2.8 on 2022-01-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0030_auto_20220119_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs_Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faqs_title', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_title', models.CharField(blank=True, max_length=100, null=True)),
                ('faqs_text', models.TextField(blank=True, max_length=5000, null=True)),
                ('terms_text', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
