# Generated by Django 3.2.8 on 2022-01-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0031_faqs_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscribers',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
    ]
