# Generated by Django 3.2.8 on 2022-01-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0033_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, default='pro.png', null=True, upload_to='avatars/'),
        ),
    ]
